### ISSUE TITLE
proton-c compatibility?

### ISSUE THREAD

**Issue by danielo515** [mattdibi/redox-keyboard#34]
Hello and congratulations for this great project.
I was looking for a wireless alternative to my ergodox, and this looks quite awesome.
However, now that I'm going to make an "upgrade" I would love to get rid of space limitations I currently have. Proton-c is an arduino pro micro alternative that has way more space for the firmware, and it should be a drop-in replacement.
I think it still has some problems with split keyboards, but since here we only have one keyboard maybe it is not that "split" at the end.
Do you think it will be compatible?

**Comment by mattdibi** [comment]
Hi,
I assume you're talking about the Redox Wireless.
Footprint-wise for sure. The code doesn't use the split functionalities so I think it should work.
I don't know of anybody who actually tried this though. You'll be the lucky beta tester if you proceed with this experiment :D

**Comment by danielo515** [comment]
Yes, I was talking about the redox wireless 😄
So physically it should fit. I don't see a reason why it should not work on the software level. I mean, I'm not an expert but proton-c uses the same firmware with probably just some tweaks on the settings.

By the way, do you have any picture where I can see the receiver with the arduino attached? All the pictures I found are only showing the wireless part

**Comment by mattdibi** [comment]
Here's some pics. Usually I add some female header pins to the receiver to be able to remove the Arduino in case I need it.
![20190727_161651](https://user-images.githubusercontent.com/22748355/61995651-6b616b00-b08b-11e9-9222-c596ae09bfdc.jpg)
![20190727_161703](https://user-images.githubusercontent.com/22748355/61995652-6e5c5b80-b08b-11e9-9b12-aa83f33f4d58.jpg)
![20190727_161710](https://user-images.githubusercontent.com/22748355/61995654-761c0000-b08b-11e9-8db1-c3b6cdafe87c.jpg)
![20190727_161955](https://user-images.githubusercontent.com/22748355/61995655-7fa56800-b08b-11e9-8cfe-ec8ce4ea654b.jpg)
![20190727_162005](https://user-images.githubusercontent.com/22748355/61995656-7fa56800-b08b-11e9-94f9-31f593658ed2.jpg)

In case you're wondering without those female header pins the arduino + receiver assembly should look somethink like this.

![20190727_161917](https://user-images.githubusercontent.com/22748355/61995666-a1065400-b08b-11e9-8d3a-63db47678e54.jpg)
![20190727_161928](https://user-images.githubusercontent.com/22748355/61995667-a19eea80-b08b-11e9-8725-5d23eb0cca6e.jpg)
![20190727_161935](https://user-images.githubusercontent.com/22748355/61995668-a19eea80-b08b-11e9-8e14-57b30188ff76.jpg)

Maybe a little thicker because there's the voltage regulator on the back of the receiver board.

Hope this helps.

**Comment by danielo515** [comment]
Wow, that is quite a big receiver! But I like the idea of the female pins.
Thank you very much for the pics, they helped me to get an idea about how it looks like.
