### ISSUE TITLE
Any tips on hand-wired wireless version?

### ISSUE THREAD

**Issue by Mishkun** [mattdibi/redox-keyboard#52]
I am building my second redox in the concave case found here https://www.thingiverse.com/thing:3503380

I have no options but handwired due to concave case. Yet I want to try wireless. Any tips on rows/columns connection to transmitters?

**Comment by mattdibi** [comment]
Hi,

I would suggest you to follow the schematics available so that you can use the available software without further modification. Also you might find easier to use the [Core51822](https://www.waveshare.com/core51822.htm) for handwiring since it uses 2mm pitch pins for which you can find cables online.

Hope this helps.
