### ISSUE TITLE
Share CAD files for case?

### ISSUE THREAD

**Issue by chrismelba** [mattdibi/redox-keyboard#63]
I'd like to do a bit of modelling with the case to make an ergonomic stand. I can use the STL but would be easier with a different format like .iges or .stp. Something  I can import to fusion 360

**Comment by mattdibi** [comment]
Hi,

unfortunately this is a little tricky because of The Great Loss Of Data Of 2019 (caused by a treacherous SSD) which coincided with my switch to Fusion360 from SolidWorks.

I converted the backups in .step file and will upload them shortly. Keep in mind that they might not be the latest revisions because of that SSD.

**Comment by mattdibi** [comment]
Here you go. If you need anything else let me know.
