### ISSUE TITLE
simplifying redox wireless receiver by using nRF52840 usb BLE dongle

### ISSUE THREAD

**Issue by irfn** [mattdibi/redox-keyboard#78]
currently redox wireless keyboard receiver is rather complex due to both YJ-14015 and Arduino Pro Micro.
I was wondering if  nRF52840 dongle would be a compatible receiver as its compatible with nRF51

https://www.nordicsemi.com/Products/Low-power-short-range-wireless/nRF52840
this would mean
- no assembly required
- single firmware for receiver

also the docs don't currently talk about what differences are there in the precompiled hex from mitosis receiver.

I see that there are some attempt for one other keyboards
https://github.com/chie4hao/qmk_firmware_nrf52840

**Comment by mattdibi** [comment]
Hi,

> I was wondering if nRF52840 dongle would be a compatible receiver as its compatible with nRF51

Currently no. As explained [here](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w#firmware):

>  The Redox keyboard works similarly to the Mitosis keyboard: we have two transmitters responsible for scanning the two matrices, which then transmit the matrix status through the Gazel protocol to the receiver. The receiver is another YJ-14015 which receives the two matrix scans and send it through serial to the Arduino Pro Micro. The Pro Micro is responsible for running QMK and converting the bytes received by the YJ-14015 into actual keystrokes.

By having everything on the same device we should run the receiver FW *and* QMK on the nRF52840 which means that we should add inside QMK the support for the Gazel protocol and that simply isn't possible due to licensing issues.

> also the docs don't currently talk about what differences are there in the precompiled hex from mitosis receiver.

The main difference is the buffer dimension: in the Redox we transmit more data because we have more keys than the Mitosis. We need a bigger matrix to represent the current pressed keys.
